import { Product, Order } from '../types'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Planșă Nisip - Fluturi Colorați',
    description: 'Un kit creativ cu 3 planșe de nisip cu fluturi, perfect pentru copiii care încep să exploreze culorile. Include nisip colorat în 6 culori vibrante și un instrument de aplicare.',
    price: 45,
    compare_price: 55,
    show_compare_price: true,
    sku: 'SNS-001',
    stock_qty: 23,
    category: 'Planșe Simple',
    age_range: '2-4',
    difficulty: 'Ușor',
    images: [
      'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=600&q=80',
      'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=600&q=80',
    ],
    status: 'active',
    weight: 300,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Kit Complet - Grădina Fermecată',
    description: 'Kit complet cu 5 planșe de nisip tematice cu flori și animale din grădină. Include nisip în 8 culori, 2 instrumente de aplicare și un suport de expunere.',
    price: 89,
    compare_price: 110,
    show_compare_price: true,
    sku: 'KIT-002',
    stock_qty: 15,
    category: 'Kit Complet',
    age_range: '4-6',
    difficulty: 'Ușor',
    images: [
      'https://images.unsplash.com/photo-1516981442399-a91139e20ff8?w=600&q=80',
      'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80',
    ],
    status: 'active',
    weight: 600,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
  },
  {
    id: '3',
    name: 'Planșă Nisip - Animale Safari',
    description: 'Explorează savana cu 4 planșe de nisip cu animale exotice. Elefanți, girafe, lei și zebre așteaptă să prindă culoare sub mâinile micuților artiști.',
    price: 59,
    sku: 'SNS-003',
    stock_qty: 8,
    category: 'Planșe Simple',
    age_range: '4-6',
    difficulty: 'Mediu',
    images: [
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80',
    ],
    status: 'active',
    weight: 400,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T10:00:00Z',
  },
  {
    id: '4',
    name: 'Kit Complet - Univers și Stele',
    description: 'Călătorește prin galaxie cu 6 planșe de nisip cu planete, stele și rachete. Kit premium cu nisip sidefat în 10 culori, perfect pentru copiii mai mari.',
    price: 125,
    sku: 'KIT-004',
    stock_qty: 12,
    category: 'Kit Complet',
    age_range: '6-8',
    difficulty: 'Mediu',
    images: [
      'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600&q=80',
    ],
    status: 'active',
    weight: 750,
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2024-02-10T10:00:00Z',
  },
  {
    id: '5',
    name: 'Nisip Colorat Premium - Set 12 Culori',
    description: 'Set de reîncărcare cu nisip colorat de înaltă calitate, non-toxic și sigur pentru copii. 12 culori vibrante în pungi resigillabile de 50g fiecare.',
    price: 38,
    sku: 'NSP-005',
    stock_qty: 45,
    category: 'Nisip Colorat',
    age_range: '2-4',
    difficulty: 'Ușor',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    ],
    status: 'active',
    weight: 700,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-02-15T10:00:00Z',
  },
  {
    id: '6',
    name: 'Kit Avansat - Mandale și Geometrie',
    description: 'Pentru copiii creativi și răbdători. 8 planșe complexe de nisip cu motive de mandale și forme geometrice. Include ghid de tehnici avansate de colorare.',
    price: 149,
    sku: 'KIT-006',
    stock_qty: 6,
    category: 'Kit Complet',
    age_range: '8-10',
    difficulty: 'Avansat',
    images: [
      'https://images.unsplash.com/photo-1605106702734-205df224ecce?w=600&q=80',
    ],
    status: 'active',
    weight: 900,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
  },
  {
    id: '7',
    name: 'Planșă Nisip - Principese și Castele',
    description: 'Trei planșe magice cu principese, castele și unicorni pentru micile prințese. Culorile pastelate și detaliile fine vor captiva imaginația copilului.',
    price: 49,
    compare_price: 60,
    show_compare_price: false,
    sku: 'SNS-007',
    stock_qty: 0,
    category: 'Planșe Simple',
    age_range: '4-6',
    difficulty: 'Ușor',
    images: [
      'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=600&q=80',
    ],
    status: 'out_of_stock',
    weight: 350,
    created_at: '2024-03-05T10:00:00Z',
    updated_at: '2024-03-05T10:00:00Z',
  },
  {
    id: '8',
    name: 'Accesorii Premium - Set Pensule și Spatule',
    description: 'Set de accesorii profesionale pentru planșele de nisip: 5 pensule de diferite grosimi, 3 spatule de nivelare și 1 suflător pentru detalii fine.',
    price: 28,
    sku: 'ACC-008',
    stock_qty: 30,
    category: 'Accesorii',
    age_range: '6-8',
    difficulty: 'Mediu',
    images: [
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80',
    ],
    status: 'active',
    weight: 150,
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-03-10T10:00:00Z',
  },
]

export const mockOrders: Order[] = [
  {
    id: 'ORD-2024-001',
    customer_email: 'mama.elena@gmail.com',
    customer_name: 'Elena Popescu',
    customer_phone: '+40 722 345 678',
    shipping_address: {
      name: 'Elena Popescu',
      street: 'Str. Florilor 12, Ap. 3',
      city: 'Cluj-Napoca',
      county: 'Cluj',
      postal_code: '400001',
      country: 'România',
    },
    items: [
      { id: '1', order_id: 'ORD-2024-001', product_id: '1', product_name: 'Planșă Nisip - Fluturi Colorați', quantity: 2, unit_price: 45 },
    ],
    total: 99,
    shipping_cost: 9,
    payment_status: 'paid',
    order_status: 'Livrată',
    payment_method: 'card',
    created_at: '2024-03-01T14:30:00Z',
  },
  {
    id: 'ORD-2024-002',
    customer_email: 'tata.mihai@yahoo.ro',
    customer_name: 'Mihai Ionescu',
    customer_phone: '+40 733 456 789',
    shipping_address: {
      name: 'Mihai Ionescu',
      street: 'Bd. Unirii 45',
      city: 'București',
      county: 'Ilfov',
      postal_code: '030001',
      country: 'România',
    },
    items: [
      { id: '2', order_id: 'ORD-2024-002', product_id: '4', product_name: 'Kit Complet - Univers și Stele', quantity: 1, unit_price: 125 },
      { id: '3', order_id: 'ORD-2024-002', product_id: '8', product_name: 'Accesorii Premium', quantity: 1, unit_price: 28 },
    ],
    total: 153,
    shipping_cost: 0,
    payment_status: 'paid',
    order_status: 'Expediată',
    payment_method: 'card',
    created_at: '2024-03-10T09:15:00Z',
  },
  {
    id: 'ORD-2024-003',
    customer_email: 'gradinita@educatieplus.ro',
    customer_name: 'Grădinița Educație Plus',
    customer_phone: '+40 21 345 6789',
    shipping_address: {
      name: 'Grădinița Educație Plus',
      street: 'Str. Copilăriei 7',
      city: 'Timișoara',
      county: 'Timiș',
      postal_code: '300001',
      country: 'România',
    },
    items: [
      { id: '4', order_id: 'ORD-2024-003', product_id: '2', product_name: 'Kit Complet - Grădina Fermecată', quantity: 5, unit_price: 89 },
    ],
    total: 445,
    shipping_cost: 0,
    payment_status: 'pending',
    order_status: 'Nouă',
    payment_method: 'ramburs',
    created_at: '2024-03-15T11:00:00Z',
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Maria C.',
    role: 'Mamă a doi copii',
    text: 'Fiica mea de 5 ani a stat concentrată 45 de minute! Niciodată nu am văzut-o atât de absorbită într-o activitate. Calitatea nisipului e excepțională.',
    rating: 5,
    avatar: 'MC',
  },
  {
    id: 2,
    name: 'Prof. Andreea M.',
    role: 'Educatoare la Grădinița Steluța',
    text: 'Folosim kiturile Sensoria la activitățile de dezvoltare senzorială. Copiii adoră, iar eu observ îmbunătățiri clare în motricitatea fină și capacitatea de concentrare.',
    rating: 5,
    avatar: 'AM',
  },
  {
    id: 3,
    name: 'Radu și Alexandra T.',
    role: 'Părinți, Cluj-Napoca',
    text: 'Am cumpărat kitul de Safari pentru băiețelul nostru de 4 ani. E o activitate pe care o facem împreună în weekend — relaxant și pentru noi! Recomandăm cu căldură.',
    rating: 5,
    avatar: 'RT',
  },
  {
    id: 4,
    name: 'Ioana B.',
    role: 'Mamă și psihoterapeut pentru copii',
    text: 'Ca specialist în sănătate mentală, apreciez mult beneficiile terapeutice ale acestor kituri. Le recomand familiilor care lucrează la reglarea emoțională cu copiii lor.',
    rating: 5,
    avatar: 'IB',
  },
]
